### PR TITLE
tests/libscrypt-kdf: trivial style fix

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
I suppose that it was inevitable that I'd forget to run my "find style violations" script.  :(

**Comment by cperciva** [comment]
If we're going to make this stylish, how about giving `main` some arguments?  We'll ignore them, but they should be there...

**Comment by gperciva** [comment]
really?  hmm... is `main(void)` allowed?  We use that a bunch in `libcperciva/POSIX/`.

**Comment by cperciva** [comment]
I think `C99` allows both `int main(void)` and `int main(int argc, char * argv[])` but not `int main()`.  But check the standard to make sure...

**Comment by gperciva** [comment]
Yeah, the spec says `int main(void)` or the usual `argc, argv` thing.  Updated PR.

**Pull request merged**
