### PR TITLE
keep the comment style uniform

### PR DESCRIPTION
**Pull request by Alanscut**

### CODE REVIEW

**Comment by gperciva** [comment]
Thanks for the interest, @Alanscut!

The comments are not quite as inconsistent as they may appear, but unfortunately our `STYLE` document isn't part of the repository.  :(  My apologies for that, I'll start working on it.

A fairly recent copy of our `STYLE` is here:
https://github.com/Tarsnap/libcperciva/blob/master/STYLE
and it states that we use the FreeBSD style in general, such as:
https://man.openbsd.org/FreeBSD-11.1/style.9

From the FreeBSD style,
```
/*
 * Multi-line comments look like this.  Make them real sentences.  Fill
 * them so they look like real paragraphs.
 */
```

The libcperciva style asks for function-describing comments like this:
```
/**
 * module_func(arg1, arg2):
 * Description of what the function does, referring to arguments as
 * ${arg1} or suchlike.
 */
int module_func(void *, int);
```

which is where the apparent inconsistency arises.  But because we forgot to include that in this repository, there was no way that you'd know that.  Sorry again!

There is one final inconsistency: if we have a multi-line paragraph which has deliberate line-breaks (such as two paragraphs or a paragraph plus a code example), we either use
```
/**
 * blah
 *
 * more blah
 */
```

OR

```
/*-
 * blah
 *
 * more blah
 */
```

So far I've been unable to figure out why we have `/**` vs. `/*-` for those comments (copyright statements use `/*-` as per the FreeBSD style).  I'll continue to investigate.

**Comment by cperciva** [comment]
The different style for "unrewrappable" comments is based on whether they're in the first column or not.  `/*-` comments starting in the first column are reserved for copyright statements.

**Comment by gperciva** [comment]
```
td@beastie: ~/src/tarsnap (master)
$ git grep "\/\*-" -- "*.c" | grep -v ":\/"
lib/crypto/crypto_rsa.c:		/*-
lib/netproto/netproto_keyexchange.c:	/*-
libarchive/archive_write_set_format_pax.c:	/*-
tar/multitape/chunkify.c:	/*-
td@beastie: ~/src/tarsnap (master)
$ 
```

**Comment by gperciva** [comment]
Wait, now I'm more confused.

```
$ git grep "\/\*\*" -- "*.c" | grep -v ":\/"
lib/network/tsnetwork_connect.c:	/**
libcperciva/crypto/crypto_aes_aesni.c:	/**
libcperciva/crypto/crypto_aes_aesni.c:	/**
tar/ccache/ccache_read.c:	/**
tar/ccache/ccache_write.c:	/**
tar/chunks/chunks_directory.c:	/**
td@beastie: ~/src/tarsnap (master)
$ 
```

Of the not-in-the-first-column comments, there's 3 non-libarchive which start with `/*-`, and 6 which start `/**`.  Should they be consistent, and if so, which one is correct?

**Comment by cperciva** [comment]
`/**` should only be used in the first column.  It should be `/*-` in other columns, since there's no risk of non-first-column comments being interpreted as copyright statements.

... I didn't say that I always got this right.

**Comment by gperciva** [comment]
Ok, I just wanted to know what to add to `STYLE`.

**Comment by Alanscut** [comment]
Thank Graham @gperciva  and Colin @cperciva  for letting me know more about commet style!

**Comment by gperciva** [comment]
Hi @Alanscut, we now have the `STYLE` document in this repository, added in #210.  Sorry again for not having it earlier!

**Comment by Alanscut** [comment]
Hi  Graham @gperciva,  I am very sorry for bringing you so much trouble. 
I just noticed some comment style changes in your submission(https://github.com/Tarsnap/scrypt/commit/365f192cd6d68a957b47295c62ba16f1158f1607), but I found that some comments still do not match the style which you modified in the commit. This made me mistakenly think that you just modified part of the comment becauseof negligence, so I send a PR to help you change it.

**Comment by gperciva** [comment]
Hi @Alanscut, this was no trouble at all!  We strive for very high-quality software, and I learned some stuff (and saw problems in other repositories), so I'm glad that it came up.  :)

**Pull request closed without merging**
