### PR TITLE
automake version info

### PR DESCRIPTION
**Pull request by jungle-boogie**
Perhaps not the best place to put the note, but it's at least now on 'paper'.

### CODE REVIEW

**Comment by gperciva** [comment]
Thanks for the PR!  Technically, one does not need automake to build scrypt; it is only needed if building code from git instead of an official release tarball.  I wrote about that, and tweaked the formatting, in PR #80.

**Comment by jungle-boogie** [comment]
Ah, I do see that now.

However, your readme doesn't contain information on "building". I went here instead of looking for a git-building page:
https://github.com/Tarsnap/scrypt/blob/master/README.md

**Comment by gperciva** [comment]
Indeed.  PR #80 changes that page: https://github.com/Tarsnap/scrypt/tree/git-build-automake#building. Does that proposed change clarify matters?  If not, I'd like to change it to remove any confusion!  :)

(note that the README.md file is included in the official tarball releases, so it should be written so that it is applicable to both those releases and building from git)

**Comment by jungle-boogie** [comment]
Hi @gperciva,

yes, your link above is clear to me. 

Thanks for this discussion and scrypt.

Thanks,
sean

**Comment by cperciva** [comment]
I've merged #80 -- this one can be closed now, right?

**Comment by gperciva** [comment]
Right, closing it.

**Pull request closed without merging**
