### PR TITLE
Tools: switch from GPGKEYFILE to GNUPGHOME

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Addresses https://github.com/Tarsnap/scrypt/pull/51#issuecomment-221741577

**Comment by cperciva** [comment]
Can we make this require `GNUPGSIGNINGHOME` to be set, and then set `GNUPGHOME` to that value?  I could imagine GNUPGHOME being set in a general user environment; using a different name ensures that it was set deliberately for the signing operation.

**Comment by gperciva** [comment]
Do you want a generic `GNUPGSIGNINGHOME`, or `GNUPG_SCRYPT_HOME` OR `GNUPG_TARSNAP_HOME` ?  Or perhaps taking this as a command-line argument, to make extra certain that it's something set deliberately for this signing operation?

**Comment by cperciva** [comment]
Oh, yes, command-line argument.  Sorry, I was still thinking in Makefile mode where everything is variables.

The `-u $GPGKEYID` can be dropped though; the "signing" gnupg home should only have one key so it should be selected automatically.

**Comment by gperciva** [comment]
Updated PR

**Pull request merged**
