### PR TITLE
Scryptdec cookie all in main rebased

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This is a slightly tweaked version of a rebased #141.  The diff between #141 and this is:
- I also set `infile = stdin;`
- I called the label `donewithfiles`
- I didn't swap the order of closing `infile` and `outfile`, and I didn't change the comment.

Full diff against #141 is this:

```
diff --git a/main.c b/main.c
index 6d8ae7b..ccd3715 100644
--- a/main.c
+++ b/main.c
@@ -54,7 +54,7 @@ usage(void)
 int
 main(int argc, char *argv[])
 {
-	FILE * infile;
+	FILE * infile = stdin;
 	FILE * outfile = stdout;
 	int devtty = 1;
 	int dec = 0;
@@ -160,8 +160,6 @@ main(int argc, char *argv[])
 			warnp("Cannot open input file: %s", infilename);
 			goto err0;
 		}
-	} else {
-		infile = stdin;
 	}
 
 	/* Prompt for a password. */
@@ -182,7 +180,7 @@ main(int argc, char *argv[])
 		if ((rc = scryptdec_file_prep(infile, (uint8_t *)passwd,
 		    strlen(passwd), maxmem, maxmemfrac, maxtime, verbose,
 		    force_resources, &C)) != 0) {
-			goto openfailed;
+			goto donewithfiles;
 		}
 	}
 
@@ -201,7 +199,7 @@ main(int argc, char *argv[])
 		rc = scryptenc_file(infile, outfile, (uint8_t *)passwd,
 		    strlen(passwd), maxmem, maxmemfrac, maxtime, verbose);
 
-openfailed:
+donewithfiles:
 	/* Free the decryption cookie, if any. */
 	scryptdec_file_cookie_free(C);
 
@@ -209,13 +207,11 @@ openfailed:
 	insecure_memzero(passwd, strlen(passwd));
 	free(passwd);
 
-	/* Close outfile (if applicable). */
-	if (outfile != stdout)
-		fclose(outfile);
-
-	/* Close infile (if applicable). */
+	/* Close any files we opened. */
 	if (infile != stdin)
 		fclose(infile);
+	if (outfile != stdout)
+		fclose(outfile);
 
 	/* If we failed, print the right error message and exit. */
 	if (rc != 0) {
```

**Comment by cperciva** [comment]
> I also set infile = stdin;

I don't like this, because stdin *isn't a default value for infile*.  The situation is different with outfile and stdout since users can opt to not specify outfile; but infile will only be stdin if the file name is explicitly specified as "-".

**Comment by cperciva** [comment]
> I called the label donewithfiles

I'm now thinking that your original idea of "cleanup" makes the most sense.

**Comment by gperciva** [comment]
Ok, revised PR.  Diff against #141 is just the label name and the order of closing files:

```
diff --git a/main.c b/main.c
index 6d8ae7b..357a7d6 100644
--- a/main.c
+++ b/main.c
@@ -182,7 +182,7 @@ main(int argc, char *argv[])
 		if ((rc = scryptdec_file_prep(infile, (uint8_t *)passwd,
 		    strlen(passwd), maxmem, maxmemfrac, maxtime, verbose,
 		    force_resources, &C)) != 0) {
-			goto openfailed;
+			goto cleanup;
 		}
 	}
 
@@ -201,7 +201,7 @@ main(int argc, char *argv[])
 		rc = scryptenc_file(infile, outfile, (uint8_t *)passwd,
 		    strlen(passwd), maxmem, maxmemfrac, maxtime, verbose);
 
-openfailed:
+cleanup:
 	/* Free the decryption cookie, if any. */
 	scryptdec_file_cookie_free(C);
 
@@ -209,13 +209,11 @@ openfailed:
 	insecure_memzero(passwd, strlen(passwd));
 	free(passwd);
 
-	/* Close outfile (if applicable). */
-	if (outfile != stdout)
-		fclose(outfile);
-
-	/* Close infile (if applicable). */
+	/* Close any files we opened. */
 	if (infile != stdin)
 		fclose(infile);
+	if (outfile != stdout)
+		fclose(outfile);
 
 	/* If we failed, print the right error message and exit. */
 	if (rc != 0) {
```

**Pull request merged**
